-- MySQL Script generated by MySQL Workbench
-- Sat Mar 29 13:32:30 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rentaldb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `rentaldb` ;

-- -----------------------------------------------------
-- Schema rentaldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rentaldb` DEFAULT CHARACTER SET utf8 ;
USE `rentaldb` ;

-- -----------------------------------------------------
-- Table `rentaldb`.`manufacturer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rentaldb`.`manufacturer` ;

CREATE TABLE IF NOT EXISTS `rentaldb`.`manufacturer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `country` VARCHAR(100) NOT NULL,
  `address` VARCHAR(200) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `phone` VARCHAR(100) NOT NULL,
  `fax` VARCHAR(100) NULL,
  `is_deleted` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rentaldb`.`file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rentaldb`.`file` ;

CREATE TABLE IF NOT EXISTS `rentaldb`.`file` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `path` VARCHAR(200) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `is_deleted` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rentaldb`.`vehicle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rentaldb`.`vehicle` ;

CREATE TABLE IF NOT EXISTS `rentaldb`.`vehicle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `vehicle_code` VARCHAR(45) NOT NULL,
  `purchase_price` DOUBLE NOT NULL,
  `model` VARCHAR(200) NOT NULL,
  `status` ENUM('Available', 'Rented', 'Broken') NOT NULL,
  `is_deleted` TINYINT NOT NULL,
  `manufacturer_id` INT NOT NULL,
  `vehicle_picture_id` INT NOT NULL,
  PRIMARY KEY (`id`, `vehicle_picture_id`),
  INDEX `fk_vehicle_manufacturer_idx` (`manufacturer_id` ASC) VISIBLE,
  INDEX `fk_vehicle_file1_idx` (`vehicle_picture_id` ASC) VISIBLE,
  CONSTRAINT `fk_vehicle_manufacturer`
    FOREIGN KEY (`manufacturer_id`)
    REFERENCES `rentaldb`.`manufacturer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicle_file1`
    FOREIGN KEY (`vehicle_picture_id`)
    REFERENCES `rentaldb`.`file` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rentaldb`.`car`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rentaldb`.`car` ;

CREATE TABLE IF NOT EXISTS `rentaldb`.`car` (
  `id` INT NOT NULL,
  `acquisition_date` DATETIME NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_car_vehicle1`
    FOREIGN KEY (`id`)
    REFERENCES `rentaldb`.`vehicle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rentaldb`.`electric_bike`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rentaldb`.`electric_bike` ;

CREATE TABLE IF NOT EXISTS `rentaldb`.`electric_bike` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `range_per_charge` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_electric_bike_vehicle1`
    FOREIGN KEY (`id`)
    REFERENCES `rentaldb`.`vehicle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rentaldb`.`electric_scooter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rentaldb`.`electric_scooter` ;

CREATE TABLE IF NOT EXISTS `rentaldb`.`electric_scooter` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `max_speed` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_electric_scooter_vehicle1`
    FOREIGN KEY (`id`)
    REFERENCES `rentaldb`.`vehicle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rentaldb`.`malfunction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rentaldb`.`malfunction` ;

CREATE TABLE IF NOT EXISTS `rentaldb`.`malfunction` (
  `id` INT NOT NULL,
  `date` DATE NOT NULL,
  `time` TIME NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `is_deleted` TINYINT NOT NULL,
  `vehicle_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_malfunction_vehicle1_idx` (`vehicle_id` ASC) VISIBLE,
  CONSTRAINT `fk_malfunction_vehicle1`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `rentaldb`.`vehicle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rentaldb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rentaldb`.`user` ;

CREATE TABLE IF NOT EXISTS `rentaldb`.`user` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(300) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `profile_picture_id` INT NOT NULL,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_user_file1_idx` (`profile_picture_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_file1`
    FOREIGN KEY (`profile_picture_id`)
    REFERENCES `rentaldb`.`file` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rentaldb`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rentaldb`.`employee` ;

CREATE TABLE IF NOT EXISTS `rentaldb`.`employee` (
  `id` INT NOT NULL,
  `role` ENUM('Admin', 'Operator', 'Manager') NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_employee_user1`
    FOREIGN KEY (`id`)
    REFERENCES `rentaldb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rentaldb`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rentaldb`.`client` ;

CREATE TABLE IF NOT EXISTS `rentaldb`.`client` (
  `id` INT NOT NULL,
  `card_number` VARCHAR(45) NOT NULL,
  `is_blocked` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_client_user1`
    FOREIGN KEY (`id`)
    REFERENCES `rentaldb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rentaldb`.`rental`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rentaldb`.`rental` ;

CREATE TABLE IF NOT EXISTS `rentaldb`.`rental` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `start_location_lat` DOUBLE NOT NULL,
  `start_location_lng` DOUBLE NOT NULL,
  `end_location_lat` DOUBLE NOT NULL,
  `end_location_lng` DOUBLE NOT NULL,
  `duration` TIME NOT NULL,
  `identification_card` VARCHAR(100) NOT NULL,
  `driver_licence` VARCHAR(100) NULL,
  `client_id` INT NOT NULL,
  `vehicle_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rental_client1_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_rental_vehicle1_idx` (`vehicle_id` ASC) VISIBLE,
  CONSTRAINT `fk_rental_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `rentaldb`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rental_vehicle1`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `rentaldb`.`vehicle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rentaldb`.`invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rentaldb`.`invoice` ;

CREATE TABLE IF NOT EXISTS `rentaldb`.`invoice` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rental_id` INT NOT NULL,
  `pdf_file_id` INT NOT NULL,
  PRIMARY KEY (`id`, `pdf_file_id`),
  INDEX `fk_invoice_rental1_idx` (`rental_id` ASC) VISIBLE,
  INDEX `fk_invoice_file1_idx` (`pdf_file_id` ASC) VISIBLE,
  CONSTRAINT `fk_invoice_rental1`
    FOREIGN KEY (`rental_id`)
    REFERENCES `rentaldb`.`rental` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoice_file1`
    FOREIGN KEY (`pdf_file_id`)
    REFERENCES `rentaldb`.`file` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rentaldb`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rentaldb`.`post` ;

CREATE TABLE IF NOT EXISTS `rentaldb`.`post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `content` VARCHAR(500) NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
